/**
 * Hand-written shared types live here. Database row types will be generated by
 * Prisma in Phase 2 and imported from `@prisma/client`; this file is for
 * view-models and DTOs that don't map 1:1 to a table.
 */
import type { Role } from "@/lib/roles";

/** The shape we expect on the auth session once Auth.js is wired up (Phase 3). */
export type SessionUser = {
  id: string;
  name: string | null;
  email: string;
  role: Role;
};
